name: tariqi_app
description: ØªØ·Ø¨ÙŠÙ‚ Ù†Ù…Ø· Ø§Ù„Ø­ÙŠØ§Ø© Ø§Ù„Ø°ÙƒÙŠ Ù„ØªØ­Ø³ÙŠÙ† Ø±Ø­Ù„Ø§ØªÙƒ Ø§Ù„ÙŠÙˆÙ…ÙŠØ© ÙÙŠ ÙÙ„Ø³Ø·ÙŠÙ†
publish_to: "none"
# ðŸ”¥ ØªØ­Ø¯ÙŠØ« Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ø¥ØµØ¯Ø§Ø± Ù„Ù„Ù†Ø´Ø±
version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  vibration: ^3.1.3
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  fluttertoast: ^8.2.4
  intl: ^0.20.2
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  google_mobile_ads: ^5.0.0
  share_plus: ^7.2.2
  webview_flutter: ^4.4.2
  device_info_plus: ^10.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # ðŸ”¥ Ø£Ø¯ÙˆØ§Øª Ù…Ù‡Ù…Ø© Ù„Ù„Ø¨ÙŠÙ„Ø¯
  flutter_launcher_icons: ^0.13.1

# ðŸ”¥ ØªÙƒÙˆÙŠÙ† Ø£ÙŠÙ‚ÙˆÙ†Ø© Ø§Ù„ØªØ·Ø¨ÙŠÙ‚
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/assets/icon/
    - lib/assets/images/

flutter_localization:
  assets-path: l10n
  output-class: AppLocalizations
  output-dir: lib/generated
